-- Config seed (repeatable). Status graphs and job types are code-owned (overwritten);
-- settings, AI routes and prices are operator-owned (inserted once, never overwritten).

-- Status graphs (tz section 7). "Cancel is allowed from any status before publishing".
delete from status_graph;
insert into status_graph (entity, from_status, to_status) values
  ('material', 'received', 'parsed'),
  ('material', 'received', 'rejected'),
  ('material', 'parsed', 'awaiting_author'),
  ('material', 'parsed', 'routed'),
  ('material', 'parsed', 'rejected'),
  ('material', 'awaiting_author', 'routed'),
  ('material', 'awaiting_author', 'rejected'),
  ('variant', 'draft', 'pending_approval'),
  ('variant', 'pending_approval', 'revising'),
  ('variant', 'pending_approval', 'approved'),
  ('variant', 'pending_approval', 'rejected'),
  ('variant', 'revising', 'pending_approval'),
  ('variant', 'approved', 'scheduled'),
  ('variant', 'scheduled', 'publishing'),
  ('variant', 'scheduled', 'rescheduled'),
  ('variant', 'rescheduled', 'scheduled'),
  ('variant', 'publishing', 'published'),
  ('variant', 'publishing', 'failed'),
  ('variant', 'failed', 'scheduled'),
  ('variant', 'draft', 'cancelled'),
  ('variant', 'pending_approval', 'cancelled'),
  ('variant', 'revising', 'cancelled'),
  ('variant', 'approved', 'cancelled'),
  ('variant', 'scheduled', 'cancelled'),
  ('variant', 'rescheduled', 'cancelled'),
  ('variant', 'failed', 'cancelled'),
  ('digest_issue', 'draft', 'pending_approval'),
  ('digest_issue', 'draft', 'skipped'),
  ('digest_issue', 'pending_approval', 'approved'),
  ('digest_issue', 'pending_approval', 'rejected'),
  ('digest_issue', 'pending_approval', 'skipped'),
  ('digest_issue', 'approved', 'scheduled'),
  ('digest_issue', 'scheduled', 'publishing'),
  ('digest_issue', 'scheduled', 'cancelled'),
  ('digest_issue', 'publishing', 'published'),
  ('digest_issue', 'publishing', 'failed'),
  ('digest_issue', 'failed', 'scheduled'),
  ('digest_issue', 'failed', 'cancelled'),
  ('digest_issue', 'draft', 'cancelled'),
  ('digest_issue', 'pending_approval', 'cancelled'),
  ('digest_issue', 'approved', 'cancelled');

-- Job types -> n8n workflows (stable workflow ids, see n8n/workflows/*.json).
insert into job_types (type, workflow_id, max_concurrency, max_attempts, lease_seconds, backoff_seconds, budget_gated, description) values
  ('tg.update',               'acfSqlJob0000001', 8, 5,   60, 5,  false, 'Telegram update: intake, commands, buttons, dialog input'),
  ('material.seal',           'acfSqlJob0000001', 8, 5,   60, 5,  false, 'Stop gluing parts after the IN-5 window, start summarization when parts are ready'),
  ('material.clarify_timeout','acfSqlJob0000001', 4, 3,   60, 30, false, 'EX-3: no answer in 2 h -> continue with low-data flag'),
  ('part.process',            'acfPartProcess01', 6, 5,  900, 20, false, 'Download a part to S3 and turn it into text (EX-1, IN-9)'),
  ('material.summarize',      'acfSummarize0001', 6, 5,  300, 20, false, 'Summary, language, sufficiency, hints, moderation (EX-2..EX-4)'),
  ('material.route',          'acfRoute00000001', 6, 5,  300, 20, false, 'Brand detection (RT-1..RT-4)'),
  ('variant.generate',        'acfGenerate00001', 8, 5,  600, 30, true,  'Generate / redo / fix a variant (GN-1, GN-2, GN-4, GN-6)'),
  ('variant.check',           'acfCheck00000001', 8, 5,  600, 30, true,  'Automatic checks (GN-5)'),
  ('package.visual',          'acfVisual0000001', 4, 4,  900, 60, true,  'Visuals: generate or adapt, logo, vision check (GN-3)'),
  ('package.card',            'acfSqlJob0000001', 8, 5,   60, 5,  false, 'Send the package card to editors (AP-1)'),
  ('card.refresh',            'acfSqlJob0000001', 8, 5,   60, 5,  false, 'Refresh the card for all editors (AP-7)'),
  ('variant.deadline',        'acfSqlJob0000001', 4, 5,   60, 10, false, 'Approval reminders and missed-slot handling (AP-5)'),
  ('post.op',                 'acfPostOps000001', 2, 5,  120, 30, false, 'Edit or delete a published post (PB-7)'),
  ('digest.plan',             'acfSqlJob0000001', 2, 3,   60, 30, false, 'Plan the next digest issue for a brand (DG-1)'),
  ('digest.build',            'acfDigestBuild01', 2, 4,  900, 60, true,  'Build the digest issue 2 h before sending (DG-2..DG-4, DG-7)'),
  ('digest.deadline',         'acfSqlJob0000001', 2, 3,   60, 30, false, 'At send time: send if approved or auto-send, else skip (DG-4)'),
  ('digest.send',             'acfDigestSend001', 1, 10, 900, 60, false, 'Send the issue to confirmed subscribers (DG-4)'),
  ('digest.test',             'acfDigestSend001', 2, 3,  300, 30, false, 'Test send of an issue to the editor'),
  ('feeds.fetch',             'acfFeeds00000001', 2, 3,  600, 60, false, 'Fetch brand RSS sources (DG-2)'),
  ('esp.event',               'acfEspEvents0001', 1, 5,   60, 30, false, 'Resend delivery event -> verified status (DG-6)'),
  ('email.fetch',             'acfEmailFetch001', 2, 6,  300, 60, false, 'Fetch an inbound email with attachments (IN-1)'),
  ('onboarding.draft',        'acfOnboarding001', 2, 3,  900, 60, false, 'Draft brand profile from sample posts (BP-3)'),
  ('profile.import',          'acfProfileIO0001', 2, 3,  120, 30, false, 'Parse and validate an uploaded brand YAML'),
  ('profile.export',          'acfProfileIO0001', 2, 3,  120, 30, false, 'Send brand YAML to a manager'),
  ('guest.brand',             'acfGuestBrand001', 2, 3,  300, 30, false, 'Temporary guest brand from a one-line description (tz section 10)'),
  ('report.weekly',           'acfSqlJob0000001', 2, 3,  120, 60, false, 'Weekly brand report (AN-3)'),
  ('health.check',            'acfHealth0000001', 1, 1,  120, 60, false, 'System health alerts and heartbeat (AD-5)'),
  ('housekeeping',            'acfHousekeep0001', 1, 3,  900, 300, false, 'Expire guest data, sessions and temporary brands'),
  ('eval.finalize',           'acfSqlJob0000001', 1, 5,  120, 60, false, 'Compute eval run metrics when all cases finished')
on conflict (type) do update set
  workflow_id = excluded.workflow_id, max_concurrency = excluded.max_concurrency, max_attempts = excluded.max_attempts,
  lease_seconds = excluded.lease_seconds, backoff_seconds = excluded.backoff_seconds,
  budget_gated = excluded.budget_gated, description = excluded.description;

-- Settings: tz thresholds are "starting values" -> data, global with per-brand override.
insert into settings (key, value, description) values
  ('intake.glue_seconds', '60', 'IN-5 glue window'),
  ('intake.max_text_chars', '20000', 'IN-2'),
  ('intake.max_audio_seconds', '600', 'IN-2'),
  ('intake.max_file_bytes', '20971520', 'IN-2 (20 MB; also the Telegram bot download limit)'),
  ('intake.max_images', '10', 'IN-2'),
  ('intake.max_doc_pages', '30', 'IN-2'),
  ('intake.max_table_rows', '500', 'IN-2, IN-9'),
  ('intake.duplicate_days', '30', 'IN-6'),
  ('intake.duplicate_similarity', '0.85', 'IN-6 trigram similarity for near duplicates'),
  ('extract.clarify_timeout_minutes', '120', 'EX-3'),
  ('route.confidence_threshold', '0.75', 'RT-2'),
  ('gen.max_fix_attempts', '2', 'GN-6'),
  ('gen.repeat_topic_days', '14', 'GN-5'),
  ('gen.repeat_topic_similarity', '0.88', 'GN-5 cosine similarity'),
  ('gen.feedback_examples', '6', 'AP-4 examples per generation'),
  ('approval.reminder_hours', '[12, 1]', 'AP-5'),
  ('publish.retry_window_minutes', '30', 'PB-5'),
  ('publish.unknown_after_seconds', '180', 'Pending attempt older than this = unknown outcome, no auto retry'),
  ('jobs.max_running', '16', 'Global concurrency of job handlers'),
  ('budget.warn_ratio', '0.8', 'AD-4'),
  ('guest.daily_materials', '3', 'tz section 10'),
  ('guest.monthly_budget_usd', '15', 'tz section 10'),
  ('guest.temp_brand_ttl_hours', '72', 'Temporary guest brands are deleted after this'),
  ('guest.data_ttl_days', '7', 'Guest materials and assets are deleted after this'),
  ('eval.monthly_budget_usd', '40', 'Eval account'),
  ('system.monthly_budget_usd', '40', 'Pre-routing work: STT, summaries, brand detection'),
  ('notify.published_batch_minutes', '15', 'Published notifications summary window'),
  ('health.queue_depth_alert', '300', 'AD-5'),
  ('health.queue_age_alert_minutes', '15', 'AD-5'),
  ('health.error_rate_alert', '0.25', 'AD-5 share of failed AI calls / jobs in the last hour'),
  ('health.heartbeat_url', '""', 'Dead man''s switch URL pinged every 5 minutes (empty = off)'),
  ('digest.build_hours_before', '2', 'DG-4'),
  ('digest.min_blocks', '2', 'DG-7'),
  ('digest.max_blocks', '7', 'DG-3'),
  ('digest.max_feed_blocks', '2', 'DG-2 topics from external sources per issue'),
  ('digest.feed_relevance', '0.35', 'DG-2 minimum cosine similarity to the brand'),
  ('panel.magic_link_ttl_minutes', '15', 'tz 7.11'),
  ('panel.session_days', '7', 'tz 7.11'),
  ('invite.ttl_hours', '72', 'AD-2'),
  ('report.weekly_dow', '1', 'AN-3 ISO day of week (1 = Monday)'),
  ('report.weekly_time', '"09:00"', 'AN-3 local time'),
  ('api.telegram_base', '"http://egress:8081/tg"', 'Bot API through the token-injecting egress proxy'),
  ('api.telegram_file_base', '"http://egress:8081/tgfile"', 'File downloads through the egress proxy'),
  ('api.anthropic_base', '"https://api.anthropic.com"', ''),
  ('api.openrouter_base', '"https://openrouter.ai/api/v1"', ''),
  ('api.resend_base', '"https://api.resend.com"', ''),
  ('api.extractor_base', '"http://extractor:8080"', ''),
  ('s3.bucket', '"acf"', ''),
  ('web.public_url', '"http://localhost:3001"', 'Panel, previews, blogs without own domain'),
  ('bot.username', '""', 'Filled by scripts/tg-set-webhook.sh (getMe)'),
  ('email.from', '"AI Content Factory <digest@example.com>"', 'System emails sender (verified domain in Resend)'),
  ('email.inbound_domain', '"in.example.com"', 'Personal intake addresses: in+<token>@domain')
on conflict do nothing;

insert into ai_routes (route, provider, kind, model, params, prompt_route, schema_name) values
  ('extract.summary',    'anthropic',  'text',      'claude-opus-5-5', '{"effort": "low", "max_tokens": 6000}',    'extract.summary',    'extract.summary'),
  ('route.classify',     'anthropic',  'text',      'claude-opus-5-5', '{"effort": "low", "max_tokens": 2000}',    'route.classify',     'route.classify'),
  ('gen.variant',        'anthropic',  'text',      'claude-opus-5-5', '{"effort": "medium", "max_tokens": 12000}', 'gen.variant',        null),
  ('fix.variant',        'anthropic',  'text',      'claude-opus-5-5', '{"effort": "medium", "max_tokens": 12000}', 'fix.variant',        null),
  ('check.facts',        'anthropic',  'text',      'claude-opus-5-5', '{"effort": "medium", "max_tokens": 6000}',  'check.facts',        'check.facts'),
  ('image.brief',        'anthropic',  'text',      'claude-opus-5-5', '{"effort": "low", "max_tokens": 1500}',    'image.brief',        'image.brief'),
  ('vision.describe',    'anthropic',  'text',      'claude-opus-5-5', '{"effort": "low", "max_tokens": 2000}',    'vision.describe',    'vision.describe'),
  ('vision.check_image', 'anthropic',  'text',      'claude-opus-5-5', '{"effort": "low", "max_tokens": 1000}',    'vision.check_image', 'vision.check_image'),
  ('vision.pdf',         'anthropic',  'text',      'claude-opus-5-5', '{"effort": "low", "max_tokens": 32000}',   'vision.pdf',         null),
  ('digest.compose',     'anthropic',  'text',      'claude-opus-5-5', '{"effort": "medium", "max_tokens": 4000}',  'digest.compose',     'digest.compose'),
  ('digest.feed_block',  'anthropic',  'text',      'claude-opus-5-5', '{"effort": "low", "max_tokens": 2000}',    'digest.feed_block',  'gen.email_block'),
  ('onboarding.profile', 'anthropic',  'text',      'claude-opus-5-5', '{"effort": "high", "max_tokens": 16000}',  'onboarding.profile', 'brand-profile'),
  ('onboarding.quick',   'anthropic',  'text',      'claude-opus-5-5', '{"effort": "low", "max_tokens": 10000}',   'onboarding.quick',   'brand-profile'),
  ('stt',                'openrouter', 'stt',       'openai/whisper-large-v3-turbo', '{}', null, null),
  ('image.generate',     'openrouter', 'image',     'google/gemini-2.5-flash-image', '{}', null, null),
  ('embed',              'openrouter', 'embedding', 'openai/text-embedding-3-small', '{"dimensions": 1536}', null, null)
on conflict (route) do nothing;

-- Anthropic list prices per 1M tokens (cache write 5 min = 1.25x input). OpenRouter returns usage.cost itself.
insert into ai_prices (provider, model, unit, usd) values
  ('anthropic', 'claude-opus-5-5', 'mtok_in', 4.00), ('anthropic', 'claude-opus-5-5', 'mtok_out', 20.00),
  ('anthropic', 'claude-opus-5-5', 'mtok_cache_write', 5.00), ('anthropic', 'claude-opus-5-5', 'mtok_cache_read', 0.20),
  ('anthropic', 'claude-opus-5', 'mtok_in', 5.00), ('anthropic', 'claude-opus-5', 'mtok_out', 25.00),
  ('anthropic', 'claude-opus-5', 'mtok_cache_write', 6.25), ('anthropic', 'claude-opus-5', 'mtok_cache_read', 0.50),
  ('anthropic', 'claude-sonnet-5-5', 'mtok_in', 2.00), ('anthropic', 'claude-sonnet-5-5', 'mtok_out', 10.00),
  ('anthropic', 'claude-sonnet-5-5', 'mtok_cache_write', 2.50), ('anthropic', 'claude-sonnet-5-5', 'mtok_cache_read', 0.20),
  ('anthropic', 'claude-haiku-4-5', 'mtok_in', 1.00), ('anthropic', 'claude-haiku-4-5', 'mtok_out', 5.00),
  ('anthropic', 'claude-haiku-4-5', 'mtok_cache_write', 1.25), ('anthropic', 'claude-haiku-4-5', 'mtok_cache_read', 0.10)
on conflict do nothing;
