#!/usr/bin/env bash
# Create the n8n credentials the workflows reference (stable ids), only those that don't exist yet — never overwrites.
# Local service secrets come from .env (generated by setup-env.sh). External API keys come from .env if the operator put
# them there; otherwise a placeholder is created and the operator pastes the real key in the n8n UI (Credentials).
# Values are never printed or passed on a command line.
set -euo pipefail
cd "$(dirname "$0")/.."
set -a; . ./.env; set +a
EXISTING=$(docker compose exec -T postgres psql -X -tA -U postgres -d n8n -c "select id from credentials_entity")
export EXISTING
umask 077
tmp=$(mktemp)
trap 'rm -f "$tmp"' EXIT
OUT="$tmp" python3 - <<'PY'
import json, os
e = os.environ.get
have = set(e('EXISTING', '').split())
ph = 'FILL_IN_IN_N8N_UI'
creds = [
  ('acfCredPostgres1', 'ACF Postgres (app_n8n)', 'postgres', {
    'host': 'postgres', 'port': 5432, 'database': 'app', 'user': 'app_n8n', 'password': e('APP_N8N_PASSWORD'),
    'ssl': 'disable', 'maxConnections': 20}),
  ('acfCredS30000001', 'ACF S3 (RustFS)', 's3', {
    'endpoint': 'http://s3:9000', 'region': 'us-east-1', 'accessKeyId': e('S3_ACCESS_KEY'),
    'secretAccessKey': e('S3_SECRET_KEY'), 'forcePathStyle': True}),
  ('acfCredAnthropic', 'Anthropic API', 'anthropicApi', {
    'apiKey': e('ANTHROPIC_API_KEY') or ph, 'url': 'https://api.anthropic.com',
    'allowedHttpRequestDomains': 'domains', 'allowedDomains': 'api.anthropic.com,stub'}),
  ('acfCredOpenRoutr', 'OpenRouter API', 'openRouterApi', {
    'apiKey': e('OPENROUTER_API_KEY') or ph, 'allowedHttpRequestDomains': 'domains', 'allowedDomains': 'openrouter.ai,stub'}),
  ('acfCredResend001', 'Resend API (Authorization: Bearer re_...)', 'httpHeaderAuth', {
    'name': 'Authorization', 'value': 'Bearer ' + (e('RESEND_API_KEY') or ph),
    'allowedHttpRequestDomains': 'domains', 'allowedDomains': 'api.resend.com,stub'}),
  ('acfCredTgHook001', 'Telegram webhook secret', 'httpHeaderAuth', {
    'name': 'X-Telegram-Bot-Api-Secret-Token', 'value': e('TELEGRAM_WEBHOOK_SECRET')}),
  ('acfCredWebCmd001', 'Web command secret', 'httpHeaderAuth', {
    'name': 'X-ACF-Secret', 'value': e('WEB_CMD_SECRET')}),
]
out = [{'id': i, 'name': n, 'type': t, 'data': d} for i, n, t, d in creds if i not in have]
for c in out:
    if any(v in (None, '') for v in c['data'].values()):
        raise SystemExit(f"missing .env value for credential {c['name']} (run scripts/setup-env.sh)")
    note = '  <- paste the real key in the n8n UI' if ph in json.dumps(c['data']) else ''
    print(f"n8n credential to create: {c['name']} ({c['id']}){note}")
with open(e('OUT'), 'w') as f:
    json.dump(out, f)
if not out:
    print('n8n credentials: all present')
PY
if [ "$(cat "$tmp")" != "[]" ]; then
  docker compose exec -T n8n sh -c 'umask 077; f=/tmp/acf-creds.json; cat > $f; n8n import:credentials --input=$f >/dev/null; rc=$?; rm -f $f; exit $rc' < "$tmp"
  echo "n8n credentials: created"
fi
